name: Deploy Backend with Docker

on:
  push:
    branches:
    - main
    paths:
    - 'backend/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Check install
        run: cosign version

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.2.0
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          context: ./backend/MainEvent/MainEventBackend/
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-app:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-dev-do-list-build
          aws-region: eu-west-1

      - name: Package code
        run: zip -r ../site.zip *
        working-directory: backend/MainEvent

      - name: Upload artifact to S3
        run: aws s3 cp site.zip s3://${{ secrets.BACKEND_BUCKET_NAME }}/application-${{ github.run_id }}.zip
        working-directory: backend

  deploy-app:
    runs-on: ubuntu-latest
    needs: build-app

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-dev-do-list-build
          aws-region: eu-west-1

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.BACKEND_APP_NAME }} --version-label ${{ github.run_id }} --source-bundle S3Bucket="${{ secrets.BACKEND_BUCKET_NAME }}",S3Key="application-${{ github.run_id }}.zip"
          aws elasticbeanstalk update-environment --application-name ${{ secrets.BACKEND_APP_NAME }} --environment-name ${{ secrets.BACKEND_ENV_NAME }} --version-label ${{ github.run_id }}
